### PR TITLE
FIX: Unify processing

### PR DESCRIPTION
**Pull request by larsoner**
The only "bug" in your code was that you should only do the assert when `zero_phase is True`... the assert was being done even for the `zero_phase = False` bits of code, which makes sense that it failed...

While I was at it, I moved the modification of `h_fft` to where it should work with CUDA, and unified how the chunks are processed. Tests pass over here, so feel free to open the mne-python PR after merging this if you're happy.

### CODE REVIEW

**Comment by rkmaddox** [comment]
Yikes. Thanks for catching that. I think I would have burned several more hours before finding it.

In unifying how the chunks are processed, won't it make non zero-phase runs take longer? Basically the pre-padding will make for shorter segments, which will make for more segments. To be fair though, I haven't looked closely at the code and it is my bedtime. Will look closer tomorrow.

**Comment by larsoner** [comment]
No, the pre and post padding amounts are different for the two modes. For
non ZP, they are the same pads as in current master. Your indexing code was
good enough that once I turned pre and post padding into variables, the
accessing / accumulation worked automatically for the non ZP mode.

Also, can you add a brief comment about the equivalence between this and
the old filter flip filter flip method, e.g. with an explanation from
associative / commutative and conjugation as time reversal? We'll want to
have that before merging into master.

**Comment by rkmaddox** [comment]
Ah, very nice. I'll merge, test, add the comments, and submit the PR (son-permitting).

**Comment by rkmaddox** [comment]
So I tested it on my work machine and there is an array size problem in the CUDA code. I have to switch gears for a few hours bu might be able to come back to it this afternoon for a little bit. Here is the output and traceback:

``` python
Test our private overlap-add filtering function ... time: 1 sec
Test CUDA-based filtering ... Traceback (most recent call last):
  File ".../mne-python/mne/tests/test_filter.py", line 339, in <module>
    run_tests_if_main()
  File ".../mne-python/mne/utils.py", line 1660, in run_tests_if_main
    val()
  File ".../mne-python/mne/tests/test_filter.py", line 297, in test_cuda
    filter_length=fl, verbose='INFO')
  File "<string>", line 2, in band_pass_filter
  File ".../mne-python/mne/utils.py", line 537, in verbose
    return function(*args, **kwargs)
  File ".../mne-python/mne/filter.py", line 651, in band_pass_filter
    xf = _filter(x, Fs, freq, gain, filter_length, picks, n_jobs, copy)
  File ".../mne-python/mne/filter.py", line 359, in _filter
    n_jobs=n_jobs)
  File ".../mne-python/mne/filter.py", line 130, in _overlap_add_filter
    cuda_dict)
  File ".../mne-python/mne/filter.py", line 176, in _1d_overlap_filter
    prod = fft_multiply_repeated(h_fft, seg, cuda_dict)
  File ".../mne-python/mne/cuda.py", line 196, in fft_multiply_repeated
    cuda_dict['x'].set(x.astype(np.float64))
  File "/usr/lib/python2.7/dist-packages/pycuda/gpuarray.py", line 217, in set
    assert ary.size == self.size
AssertionError
```

**Comment by larsoner** [comment]
Also, are we sure that nfft > 2*len(h)-1 is the right length check? Seems
like you might need more padding, no? Or maybe that's the length at which
you can use one sample of data at a time? In that case we definitely need
to redo the nfft choosing.

**Comment by rkmaddox** [comment]
I believe that should be the length where you can do one sample of data at a time. That is obviously a very poor choice of nfft (if it ever does end up being that), but the check is there just to avoid circular overlap errors. I guess it should actually be `>=`, too?

**Comment by larsoner** [comment]
Yeah just make sure the check is correct, I'm not sure what the right value
is. I guess we should redo the profiling before merge, but I think you
should open a PR as soon as CUDA works again so that we can get feedback.
It can be WIP until we figure out the optimal fft length. Sound good?

**Comment by rkmaddox** [comment]
Yep. I'll confirm the check. I was thinking it made sense to make the fft length selection a future PR, but it is possible that some choices could make for inefficient processing due to these issues, so WIP makes sense.

**Comment by larsoner** [comment]
Yeah it originally made sense to me to do separate ones as well, but now
I'm thinking one butt kicking PR is the way to go (especially since the
line count is still small). Maybe we can get better than 2x...

**Comment by rkmaddox** [comment]
Could be. I am in array size hell right now. Don't know if I will figure it out before I go home.

Just looked at the clock. Definitely will not figure it out before I go home.

**Comment by rkmaddox** [comment]
It's some badness with the fact that CUDA FFTs are half the length of the signal because it assumes real.

**Comment by rkmaddox** [comment]
I fixed it! But I can't figure out how to get the push to work :-(

I'll spend a couple more minutes on it but then I  gotta go.

**Comment by larsoner** [comment]
Oh right, you probably need to move the conditional modification of hfft to
before the Cuda setup call is made, I assume that's how you fixed it

**Comment by rkmaddox** [comment]
OK I managed to get it up there. Git is hard. I had to make the selection of n_fft dependent on whether or not CUDA was being used. I'll add the comments tomorrow and PR as WIP noting that the chunk size will need to be fixed.

Also, since this PR is merged, but I don't have to submit PRs to my own branch, where is the proper place to discuss, e.g., my most recent commit?

**Comment by larsoner** [comment]
The normal thing would be to open a WIP PR to the main repo sooner, and do
all commenting there.

**Pull request merged**
